"""Output helpers for individual TriCube screen scripts."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from _bootstrap import ensure_import_path

ensure_import_path()

from common import environment, group_by_status, write_csv, write_json, write_summary_md  # noqa: E402


def write_single_screen(out_dir: Path, name: str, rows: list[dict[str, Any]], metadata: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    write_json(out_dir / "summary.json", {"metadata": metadata, "status_counts": group_by_status(rows), "rows": rows})
    write_csv(out_dir / f"{name}.csv", rows)
    intro = (
        "Generated by one TriCube development screen. PASS means no issue "
        "was detected under this budget; it is not a security proof."
    )
    write_summary_md(
        out_dir / f"{name}.md",
        title=name.replace("_", " ").title(),
        intro=intro,
        rows=rows,
    )
    write_summary_md(
        out_dir / "summary.md",
        title=name.replace("_", " ").title(),
        intro=intro,
        rows=rows,
    )
    print(f"wrote {out_dir}")
    print(group_by_status(rows))


def screen_metadata(**values: Any) -> dict[str, Any]:
    metadata = environment()
    metadata.update(values)
    return metadata
