"""Shared helpers for TriCube hash-mode development screens.

The stream screens in ``tests/crypto_analysis/screens`` evaluate deterministic
stream output. This module keeps hash-mode screens separate: each sample is a
message, and the tested function is the public C ``tricube_hash`` path exposed
through the CLI.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
import subprocess
import sys
from typing import Any


CRYPTO_ANALYSIS_DIR = Path(__file__).resolve().parents[1]
if str(CRYPTO_ANALYSIS_DIR) not in sys.path:
    sys.path.insert(0, str(CRYPTO_ANALYSIS_DIR))

from common import (  # noqa: E402
    C_CLI,
    REPO_ROOT,
    STATUS_BLOCKED,
    STATUS_FAIL,
    STATUS_NOT_RUN,
    STATUS_PASS,
    STATUS_WARN,
    anf_degree,
    bytes_to_bits,
    choose2,
    ensure_cli,
    environment,
    group_by_status,
    hamming_bytes,
    markdown_table,
    mean,
    rng_for,
    rotl64,
    rotate_words64,
    write_csv,
    write_json,
    write_summary_md,
    xor_bytes,
    zscore_ones,
)


HASH_IMPLEMENTATIONS = {
    "baseline_hash": "baseline_hash",
}


def parse_implementations(value: str) -> list[str]:
    implementations = [v.strip() for v in value.split(",") if v.strip()]
    for implementation in implementations:
        if implementation not in HASH_IMPLEMENTATIONS:
            raise ValueError(
                f"unknown hash implementation {implementation!r}; "
                f"expected one of {sorted(HASH_IMPLEMENTATIONS)}"
            )
    return implementations


def splitmix64(value: int) -> int:
    value = (value + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
    z = value
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
    return (z ^ (z >> 31)) & 0xFFFFFFFFFFFFFFFF


def message_from_seed(seed: int, length: int = 64) -> bytes:
    """Return a deterministic test message for a 64-bit seed."""

    state = seed & 0xFFFFFFFFFFFFFFFF
    out = bytearray()
    while len(out) < length:
        state = (state + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        out.extend(splitmix64(state).to_bytes(8, "little"))
    return bytes(out[:length])


def xor_mask_into_message(message: bytes, mask: int, offset: int = 0) -> bytes:
    """Xor a 64-bit mask into ``message`` at ``offset`` modulo message length."""

    if not message:
        message = b"\0"
    out = bytearray(message)
    start = offset % len(out)
    mask_bytes = mask.to_bytes(8, "little", signed=False)
    for idx, byte in enumerate(mask_bytes):
        out[(start + idx) % len(out)] ^= byte
    return bytes(out)


def flip_bit_in_message(message: bytes, bit_position: int) -> bytes:
    """Flip one bit at an absolute message bit position."""

    if not message:
        message = b"\0"
    out = bytearray(message)
    bit_position %= len(out) * 8
    out[bit_position // 8] ^= 1 << (bit_position % 8)
    return bytes(out)


@lru_cache(maxsize=16384)
def hash_digest(implementation: str, message: bytes) -> bytes:
    """Return the 32-byte digest from the selected TriCube hash implementation."""

    if implementation not in HASH_IMPLEMENTATIONS:
        raise ValueError(f"unknown hash implementation: {implementation}")
    ensure_cli()
    cmd = [str(C_CLI), "hash", "--hex", message.hex()]
    hex_digest = subprocess.check_output(cmd, cwd=REPO_ROOT, text=True).strip()
    return bytes.fromhex(hex_digest)


def digest_for_seed(implementation: str, seed: int, message_len: int = 64) -> bytes:
    return hash_digest(implementation, message_from_seed(seed, message_len))


def write_hash_screen_outputs(
    out_dir: Path,
    name: str,
    rows: list[dict[str, Any]],
    metadata: dict[str, Any],
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    write_json(out_dir / "summary.json", {"metadata": metadata, "status_counts": group_by_status(rows), "rows": rows})
    write_csv(out_dir / f"{name}.csv", rows)
    intro = (
        "Generated by a TriCube hash-mode development screen. PASS means no "
        "issue was detected under this budget; it is not a security proof."
    )
    write_summary_md(out_dir / f"{name}.md", title=name.replace("_", " ").title(), intro=intro, rows=rows)
    write_summary_md(out_dir / "summary.md", title=name.replace("_", " ").title(), intro=intro, rows=rows)
    print(f"wrote {out_dir}")
    print(group_by_status(rows))
