#!/usr/bin/env python3
"""Run the TriCube hash-mode development screens."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

HASH_MODE_DIR = Path(__file__).resolve().parent
if str(HASH_MODE_DIR) not in sys.path:
    sys.path.insert(0, str(HASH_MODE_DIR))

from algebraic_hash_screen import run_screen as run_algebraic_hash_screen  # noqa: E402
from collision_hash_screen import run_screen as run_collision_hash_screen  # noqa: E402
from differential_hash_screen import run_screen as run_differential_hash_screen  # noqa: E402
from hash_common import (  # noqa: E402
    STATUS_FAIL,
    environment,
    group_by_status,
    markdown_table,
    parse_implementations,
    write_csv,
    write_json,
    write_summary_md,
)
from low_bit_hash_screen import run_screen as run_low_bit_hash_screen  # noqa: E402
from rotational_hash_screen import run_screen as run_rotational_hash_screen  # noqa: E402


PROFILE_DEFAULTS = {
    "quick": {
        "samples": 64,
        "algebraic_vars": 8,
        "algebraic_bits": 32,
        "collision_samples": 512,
        "near_pairs": 256,
        "low_bit_samples": 4096,
        "message_bytes": 64,
    },
    "standard": {
        "samples": 256,
        "algebraic_vars": 10,
        "algebraic_bits": 64,
        "collision_samples": 4096,
        "near_pairs": 2048,
        "low_bit_samples": 65536,
        "message_bytes": 64,
    },
}


def write_outputs(out_dir: Path, rows_by_name: dict[str, list[dict[str, Any]]], metadata: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    all_rows = [row for rows in rows_by_name.values() for row in rows]
    write_json(out_dir / "summary.json", {"metadata": metadata, "status_counts": group_by_status(all_rows), "screens": rows_by_name})
    for name, rows in rows_by_name.items():
        write_csv(out_dir / f"{name}.csv", rows)
        write_summary_md(
            out_dir / f"{name}.md",
            title=name.replace("_", " ").title(),
            intro=(
                "Generated by TriCube hash-mode development screens. PASS means "
                "no issue was detected under this budget; it is not a security proof."
            ),
            rows=rows,
        )
    write_csv(out_dir / "all_hash_screens.csv", all_rows)
    md = [
        "# TriCube Hash-Mode Screen Summary",
        "",
        "These tests exercise the public hash API. They are development gates for obvious warning patterns, not formal cryptanalysis.",
        "",
        "## Metadata",
        "",
        markdown_table([{k: v for k, v in metadata.items() if k != "command"}]),
        "## Status Counts",
        "",
        markdown_table([group_by_status(all_rows)]),
    ]
    for name, rows in rows_by_name.items():
        md.extend([f"## {name.replace('_', ' ').title()}", "", markdown_table(rows)])
    (out_dir / "summary.md").write_text("\n".join(md), encoding="utf-8")


def run(profile: str, implementations: list[str], out_dir: Path, seed: int) -> dict[str, list[dict[str, Any]]]:
    defaults = PROFILE_DEFAULTS[profile]
    rows_by_name = {
        "differential_hash_screen": run_differential_hash_screen(
            implementations, defaults["samples"], seed, defaults["message_bytes"]
        ),
        "rotational_hash_screen": run_rotational_hash_screen(
            implementations, defaults["samples"], seed, defaults["message_bytes"]
        ),
        "algebraic_hash_screen": run_algebraic_hash_screen(
            implementations,
            defaults["algebraic_vars"],
            defaults["algebraic_bits"],
            seed,
            defaults["message_bytes"],
        ),
        "collision_hash_screen": run_collision_hash_screen(
            implementations,
            defaults["collision_samples"],
            defaults["near_pairs"],
            seed,
            defaults["message_bytes"],
        ),
        "low_bit_hash_screen": run_low_bit_hash_screen(
            implementations,
            defaults["low_bit_samples"],
            seed,
            defaults["message_bytes"],
        ),
    }
    metadata = environment()
    metadata.update({"profile": profile, "implementations": implementations, "seed": seed, **defaults})
    write_outputs(out_dir, rows_by_name, metadata)
    return rows_by_name


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=sorted(PROFILE_DEFAULTS), default="quick")
    parser.add_argument("--implementations", default="baseline_hash")
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)

    implementations = parse_implementations(args.implementations)
    rows = run(args.profile, implementations, args.out, args.seed)
    counts = group_by_status([row for screen_rows in rows.values() for row in screen_rows])
    print(f"wrote {args.out}")
    print(counts)
    return 0 if counts.get(STATUS_FAIL, 0) == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
