#!/usr/bin/env python3
"""Run all TriCube crypto-analysis development screens.

The individual screens live in ``tests/crypto_analysis/screens/`` and can be
run separately for review. This script is only the orchestration layer that
uses the same screen implementations and writes one combined summary.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

SCREEN_DIR = Path(__file__).resolve().parent / "screens"
if str(SCREEN_DIR) not in sys.path:
    sys.path.insert(0, str(SCREEN_DIR))

from common import STATUS_FAIL, environment, group_by_status, markdown_table, parse_variants, write_csv, write_json, write_summary_md
from screens.algebraic_degree_screen import run_screen as run_algebraic_degree_screen
from screens.collision_screen import run_screen as run_collision_screen
from screens.config import PROFILE_DEFAULTS
from screens.differential_screen import run_screen as run_differential_screen
from screens.external_batteries import run_screen as run_external_batteries
from screens.low_bit_diagnostics import run_screen as run_low_bit_diagnostics
from screens.overlap_fork_screen import run_screen as run_overlap_fork_screen
from screens.rotational_screen import run_screen as run_rotational_screen
from screens.state_recovery_screen import run_screen as run_state_recovery_screen


def write_outputs(out_dir: Path, rows_by_name: dict[str, list[dict[str, Any]]], metadata: dict[str, Any]) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    all_rows = [row for rows in rows_by_name.values() for row in rows]
    write_json(out_dir / "summary.json", {"metadata": metadata, "status_counts": group_by_status(all_rows), "screens": rows_by_name})
    for name, rows in rows_by_name.items():
        write_csv(out_dir / f"{name}.csv", rows)
        write_summary_md(
            out_dir / f"{name}.md",
            title=name.replace("_", " ").title(),
            intro=(
                "Generated by TriCube development screens. PASS means no issue "
                "was detected under this budget; it is not a security proof."
            ),
            rows=rows,
        )
    write_csv(out_dir / "all_screens.csv", all_rows)
    md = [
        "# TriCube Crypto-Analysis Screen Summary",
        "",
        "These tests are development gates. They can find obvious failures or warning patterns, but they do not replace white-box cryptanalysis.",
        "",
        "## Metadata",
        "",
        markdown_table([{k: v for k, v in metadata.items() if k != "command"}]),
        "## Status Counts",
        "",
        markdown_table([group_by_status(all_rows)]),
    ]
    for name, rows in rows_by_name.items():
        md.extend([f"## {name.replace('_', ' ').title()}", "", markdown_table(rows)])
    (out_dir / "summary.md").write_text("\n".join(md), encoding="utf-8")


def run(profile: str, variants: list[str], out_dir: Path, seed: int) -> dict[str, list[dict[str, Any]]]:
    defaults = PROFILE_DEFAULTS[profile]
    rows_by_name = {
        "differential_screen": run_differential_screen(variants, defaults["samples"], seed),
        "rotational_screen": run_rotational_screen(variants, defaults["samples"], seed),
        "algebraic_degree_screen": run_algebraic_degree_screen(
            variants, defaults["algebraic_vars"], defaults["algebraic_bits"], seed
        ),
        "collision_screen": run_collision_screen(variants, defaults["collision_samples"], defaults["near_pairs"], seed),
        "overlap_fork_screen": run_overlap_fork_screen(variants, defaults["stream_bytes"], seed),
        "state_recovery_screen": run_state_recovery_screen(variants, defaults["stream_bytes"], defaults["bm_bits"], seed),
        "low_bit_diagnostics": run_low_bit_diagnostics(variants, defaults["stream_bytes"], seed),
        "external_batteries": run_external_batteries(variants),
    }
    metadata = environment()
    metadata.update({"profile": profile, "variants": variants, "seed": seed, **defaults})
    write_outputs(out_dir, rows_by_name, metadata)
    return rows_by_name


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run all TriCube crypto-analysis development screens.")
    parser.add_argument("--profile", choices=sorted(PROFILE_DEFAULTS), default="quick")
    parser.add_argument("--variants", default="baseline,fast8x")
    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args(argv)

    variants = parse_variants(args.variants)
    rows = run(args.profile, variants, args.out, args.seed)
    counts = group_by_status([row for screen_rows in rows.values() for row in screen_rows])
    print(f"wrote {args.out}")
    print(counts)
    return 0 if counts.get(STATUS_FAIL, 0) == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
